PHAF parser and tests added
INCATools/ontology-access-kit pull request #476
Opened 2023-03-16 18:07 UTC by manulera

Addresses #474

Includes the parser and analogous test to that in `tests/test_parsers/test_hpoa_association_parser.py`

2023-03-16 23:52 UTC, cmungall commented
one flake8 check to fix!

you can also do a `tox -e flake8` to check locally

2023-03-16 23:53 UTC, cmungall requested changes
flake8

2023-03-17 10:07 UTC, manulera commented
I think it is fixed now, sorry about that.

2023-03-17 16:13 UTC, cmungall approved these changes

2023-03-17 16:13 UTC, merged